<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-29 18:18
=======
# Generated by Django 5.2.7 on 2025-11-27 22:01
>>>>>>> 42d12acee4145125987be89f85e05dfb264f67c0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_avaliacaoempresa'),
        ('usuarios', '0004_recuperacaosenha'),
    ]

    operations = [
    ]
